import React, { useState } from 'react';

export default function JitCompilerSandbox() {
  const [activeTab, setActiveTab] = useState<'jit' | 'static' | 'cli'>('jit');
  const [customCandidate, setCustomCandidate] = useState<string>('knds-w-[342px] hover:knds-border-hover dark:knds-bg-[#121212] sm:knds-p-400');
  const [activePresets, setActivePresets] = useState<string[]>([
    'knds-panel',
    'knds-w-[342px]',
    'hover:knds-border-hover',
    'dark:knds-bg-[#121212]',
    'sm:knds-p-400',
    'knds-grid-cols-[1fr_2fr]'
  ]);

  const allPresets = [
    { label: 'Arbitrary Width (w-[342px])', value: 'knds-w-[342px]' },
    { label: 'Arbitrary Hex Color (bg-[#121212])', value: 'knds-bg-[#121212]' },
    { label: 'Hover Variant (hover:border-hover)', value: 'hover:knds-border-hover' },
    { label: 'Dark Mode Variant (dark:w-[342px])', value: 'dark:knds-w-[342px]' },
    { label: 'Responsive Breakpoint (sm:p-400)', value: 'sm:knds-p-400' },
    { label: 'Grid Arbitrary (grid-cols-[1fr_2fr])', value: 'knds-grid-cols-[1fr_2fr]' },
    { label: 'Static Component (panel)', value: 'knds-panel' },
    { label: 'Static Button (btn-primary)', value: 'knds-btn-primary' }
  ];

  const togglePreset = (val: string) => {
    if (activePresets.includes(val)) {
      setActivePresets(activePresets.filter(item => item !== val));
    } else {
      setActivePresets([...activePresets, val]);
    }
  };

  // Simulate JIT CSS Rule Generation based on activePresets & customCandidate
  const generateSimulatedCss = () => {
    const rawTokens = new Set([
      ...activePresets,
      ...customCandidate.split(/\s+/).filter(Boolean)
    ]);

    const sortedTokens = Array.from(rawTokens).sort();
    let componentsCss: string[] = [];
    let utilitiesCss: string[] = [];

    sortedTokens.forEach(token => {
      // Static components
      if (token === 'knds-panel') {
        componentsCss.push(`.knds-panel {\n  background-color: var(--color-bg-primary);\n  border: 1px solid var(--color-border-default);\n  box-shadow: var(--shadow-hardware-bevel);\n  padding: var(--space-200);\n  border-radius: 4px;\n}`);
      } else if (token === 'knds-btn-primary') {
        componentsCss.push(`.knds-btn-primary {\n  background-color: var(--color-bg-primary);\n  border: 1px solid var(--color-border-default);\n  box-shadow: var(--shadow-hardware-bevel);\n  padding: var(--space-100) var(--space-200);\n  color: var(--color-text-primary);\n}`);
      } 
      // Arbitrary / Variant utilities
      else if (token === 'knds-w-[342px]') {
        utilitiesCss.push(`.knds-w-\\[342px\\] {\n  width: 342px;\n}`);
      } else if (token === 'knds-bg-[#121212]' || token === 'dark:knds-bg-[#121212]') {
        if (token.startsWith('dark:')) {
          utilitiesCss.push(`[data-theme='dark'] .dark\\:knds-bg-\\[\\#121212\\],\n.dark .dark\\:knds-bg-\\[\\#121212\\] {\n  background-color: #121212;\n}`);
        } else {
          utilitiesCss.push(`.knds-bg-\\[\\#121212\\] {\n  background-color: #121212;\n}`);
        }
      } else if (token === 'hover:knds-border-hover') {
        utilitiesCss.push(`.hover\\:knds-border-hover:hover {\n  border-color: var(--color-border-hover);\n}`);
      } else if (token === 'dark:knds-w-[342px]') {
        utilitiesCss.push(`[data-theme='dark'] .dark\\:knds-w-\\[342px\\],\n.dark .dark\\:knds-w-\\[342px\\] {\n  width: 342px;\n}`);
      } else if (token === 'sm:knds-p-400') {
        utilitiesCss.push(`@media (min-width: 640px) {\n  .sm\\:knds-p-400 {\n    padding: var(--space-400);\n  }\n}`);
      } else if (token === 'knds-grid-cols-[1fr_2fr]') {
        utilitiesCss.push(`.knds-grid-cols-\\[1fr_2fr\\] {\n  grid-template-columns: 1fr 2fr;\n}`);
      } else if (token.match(/^knds-[a-z0-9_-]+-\[(.+)\]$/)) {
        const m = token.match(/^knds-([a-z0-9_-]+)-\[(.+)\]$/);
        if (m) {
          const prop = m[1] === 'w' ? 'width' : m[1] === 'p' ? 'padding' : m[1] === 'h' ? 'height' : m[1] === 'bg' ? 'background-color' : m[1];
          const val = m[2].replace(/_/g, ' ');
          utilitiesCss.push(`.${token.replace(/([^a-zA-Z0-9_-])/g, '\\$1')} {\n  ${prop}: ${val};\n}`);
        }
      } else if (token.startsWith('hover:')) {
        utilitiesCss.push(`.${token.replace(/([^a-zA-Z0-9_-])/g, '\\$1')}:hover {\n  /* Simulated dynamic hover rule */\n}`);
      }
    });

    let output = `/* Generated by KNDS JIT Compiler Engine v1.0.0 */\n/* Lexical Scan Time: ~0.48ms | Candidate Tokens: ${sortedTokens.length} */\n\n`;

    if (componentsCss.length > 0) {
      output += `@layer components {\n${componentsCss.join('\n\n')}\n}\n\n`;
    }

    if (utilitiesCss.length > 0) {
      output += `@layer utilities {\n${utilitiesCss.join('\n\n')}\n}\n`;
    }

    return { css: output.trim(), count: sortedTokens.length };
  };

  const simulated = generateSimulatedCss();

  return (
    <div className="knds-panel">
      {/* Tab Header */}
      <div className="knds-flex-row knds-mb-300" style={{ borderBottom: '1px solid var(--color-border-default)', gap: '8px' }}>
        <button
          onClick={() => setActiveTab('jit')}
          className="knds-text-label-14-mono"
          style={{
            padding: '12px 20px',
            backgroundColor: activeTab === 'jit' ? 'var(--color-bg-secondary)' : 'transparent',
            border: '1px solid',
            borderColor: activeTab === 'jit' ? 'var(--color-border-default)' : 'transparent',
            borderBottom: activeTab === 'jit' ? '2px solid var(--color-functional-red)' : 'none',
            color: activeTab === 'jit' ? 'var(--color-text-primary)' : 'var(--color-text-muted)',
            fontWeight: activeTab === 'jit' ? 'bold' : 'normal',
            cursor: 'pointer'
          }}
        >
          MODE B: ON-DEMAND JIT COMPILER ENGINE
        </button>
        <button
          onClick={() => setActiveTab('static')}
          className="knds-text-label-14-mono"
          style={{
            padding: '12px 20px',
            backgroundColor: activeTab === 'static' ? 'var(--color-bg-secondary)' : 'transparent',
            border: '1px solid',
            borderColor: activeTab === 'static' ? 'var(--color-border-default)' : 'transparent',
            borderBottom: activeTab === 'static' ? '2px solid var(--color-functional-red)' : 'none',
            color: activeTab === 'static' ? 'var(--color-text-primary)' : 'var(--color-text-muted)',
            fontWeight: activeTab === 'static' ? 'bold' : 'normal',
            cursor: 'pointer'
          }}
        >
          MODE A: STATIC CDN MASTER STYLESHEET
        </button>
        <button
          onClick={() => setActiveTab('cli')}
          className="knds-text-label-14-mono"
          style={{
            padding: '12px 20px',
            backgroundColor: activeTab === 'cli' ? 'var(--color-bg-secondary)' : 'transparent',
            border: '1px solid',
            borderColor: activeTab === 'cli' ? 'var(--color-border-default)' : 'transparent',
            borderBottom: activeTab === 'cli' ? '2px solid var(--color-functional-red)' : 'none',
            color: activeTab === 'cli' ? 'var(--color-text-primary)' : 'var(--color-text-muted)',
            fontWeight: activeTab === 'cli' ? 'bold' : 'normal',
            cursor: 'pointer'
          }}
        >
          CLI & CONFIG PIPELINE
        </button>
      </div>

      {activeTab === 'jit' && (
        <div className="knds-animate-fade-in">
          <div className="knds-mb-300">
            <h3 className="knds-text-label-16 knds-mb-100">KNDS 온디맨드 JIT 컴파일러 시뮬레이터</h3>
            <p className="knds-text-copy-14 knds-text-muted">
              임의 값(Arbitrary Values: <code className="knds-text-red">[...]</code>)과 상태/반응형 수식어(Variants: <code className="knds-text-red">hover:</code>, <code className="knds-text-red">dark:</code>, <code className="knds-text-red">sm:</code>)를 Lexical Scanner가 AST 파싱 없이 0.5ms 내로 분석하여 3-Layer 규칙으로 즉시 변환하는 과정을 실시간 검증합니다.
            </p>
          </div>

          {/* Preset Chips */}
          <div className="knds-mb-300">
            <label className="knds-text-label-14-mono knds-text-muted knds-mb-100" style={{ display: 'block' }}>
              SELECT CANDIDATE PRESETS TO TEST
            </label>
            <div className="knds-flex-row knds-flex-wrap knds-gap-100">
              {allPresets.map(preset => {
                const isActive = activePresets.includes(preset.value);
                return (
                  <button
                    key={preset.value}
                    onClick={() => togglePreset(preset.value)}
                    style={{
                      padding: '6px 12px',
                      borderRadius: '4px',
                      border: '1px solid',
                      borderColor: isActive ? 'var(--color-functional-red)' : 'var(--color-border-default)',
                      backgroundColor: isActive ? 'var(--color-bg-secondary)' : 'var(--color-bg-primary)',
                      color: isActive ? 'var(--color-functional-red)' : 'var(--color-text-primary)',
                      fontSize: '13px',
                      fontFamily: 'monospace',
                      cursor: 'pointer'
                    }}
                  >
                    {isActive ? '✔ ' : '+ '}{preset.label}
                  </button>
                );
              })}
            </div>
          </div>

          {/* Custom Candidate Input */}
          <div className="knds-mb-300">
            <label className="knds-text-label-14-mono knds-text-muted knds-mb-100" style={{ display: 'block' }}>
              OR TYPE CUSTOM ARBITRARY CANDIDATE CLASSES (Space Separated)
            </label>
            <input
              type="text"
              className="knds-input"
              value={customCandidate}
              onChange={(e) => setCustomCandidate(e.target.value)}
              placeholder="e.g. knds-w-[420px] hover:knds-border-hover dark:knds-bg-[#09090b]"
            />
          </div>

          {/* Lexical Scanner & Optimization Metrics */}
          <div className="knds-grid knds-grid-cols-2 knds-gap-200 knds-mb-300">
            <div className="knds-bg-primary knds-border knds-p-200">
              <span className="knds-text-label-14-mono knds-text-red">LEXICAL SCANNER OUTPUT</span>
              <div className="knds-text-copy-14 knds-mt-100 knds-font-mono" style={{ fontSize: '13px' }}>
                <div>⏱️ Lexical Token Extraction: <strong>0.48ms</strong></div>
                <div>🔍 Valid Candidate Matches: <strong>{simulated.count} tokens</strong></div>
                <div>🛡️ Layer Order Specificity: <strong>base → components → utilities</strong></div>
              </div>
            </div>
            <div className="knds-bg-primary knds-border knds-p-200">
              <span className="knds-text-label-14-mono knds-text-red">BUNDLE SIZE OPTIMIZATION</span>
              <div className="knds-mt-100">
                <div className="knds-flex-row knds-justify-between knds-text-label-14-mono knds-mb-050" style={{ fontSize: '12px' }}>
                  <span>Monolithic Static (knds.css): 46.7 KB</span>
                  <span className="knds-text-red">JIT Bundle: ~4.57 KB (-90.2%)</span>
                </div>
                <div style={{ width: '100%', height: '12px', backgroundColor: 'var(--color-bg-secondary)', borderRadius: '6px', overflow: 'hidden', position: 'relative' }}>
                  <div style={{ width: '9.8%', height: '100%', backgroundColor: 'var(--color-functional-red)' }} />
                </div>
              </div>
            </div>
          </div>

          {/* Code Preview */}
          <div>
            <span className="knds-text-label-14-mono knds-text-muted knds-mb-100" style={{ display: 'block' }}>
              GENERATED JIT CSS (WITH ESCAPED SELECTORS & MEDIA QUERIES)
            </span>
            <pre className="knds-code-block" style={{ maxHeight: '360px', overflowY: 'auto', fontSize: '13px', lineHeight: '1.5' }}>
              {simulated.css}
            </pre>
          </div>
        </div>
      )}

      {activeTab === 'static' && (
        <div className="knds-animate-fade-in">
          <div className="knds-mb-300">
            <h3 className="knds-text-label-16 knds-mb-100">Mode A: 정적 단일 마스터 스타일시트 (CDN 방식)</h3>
            <p className="knds-text-copy-14 knds-text-muted">
              빌드 도구나 Node.js 환경 없이 <code className="knds-text-red">&lt;link&gt;</code> 태그 단 하나만으로 전체 디자인 시스템을 구동하는 아키텍처입니다. 프로토타이핑, 레거시 시스템 연동, 혹은 빌드 체인이 차단된 환경에서 즉각적인 UI 렌더링을 보장합니다.
            </p>
          </div>

          <div className="knds-bg-primary knds-border knds-p-200 knds-mb-300">
            <span className="knds-text-label-14-mono knds-text-red">HTML HEAD CDN DECLARATION</span>
            <div className="knds-code-block knds-mt-100" style={{ whiteSpace: 'pre-wrap' }}>
              {`<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/knoblab/KNDS@main/knds.css">`}
            </div>
          </div>

          <div className="knds-flex-col knds-gap-150">
            <div className="knds-bg-primary knds-border knds-p-200">
              <span className="knds-text-label-14-mono knds-font-bold">1. Zero Runtime Overhead</span>
              <p className="knds-text-copy-14 knds-mt-050 knds-text-muted">
                브라우저 네이티브 CSS 파서만을 이용하므로 JavaScript 실행 비용이 0입니다. 최초 로딩 시 46.7 KB(Gzip 시 ~11 KB)가 캐싱되면 모든 페이지에서 즉시 렌더링됩니다.
              </p>
            </div>
            <div className="knds-bg-primary knds-border knds-p-200">
              <span className="knds-text-label-14-mono knds-font-bold">2. Complete Baseline Registry</span>
              <p className="knds-text-copy-14 knds-mt-050 knds-text-muted">
                패널, 버튼, 모달, 네비게이션, 스플릿 스크린, 청사진 그리드 등 Apple HIG 기반의 100여 개 핵심 컴포넌트와 유틸리티가 모두 포함되어 있어 즉시 마크업이 가능합니다.
              </p>
            </div>
          </div>
        </div>
      )}

      {activeTab === 'cli' && (
        <div className="knds-animate-fade-in">
          <div className="knds-mb-300">
            <h3 className="knds-text-label-16 knds-mb-100">CLI 및 표준 설정 파일 (`knds.config.js`) 명세</h3>
            <p className="knds-text-copy-14 knds-text-muted">
              KNDS JIT 컴파일러는 독립 실행형 CLI 바이너리와 PostCSS 8 플러그인을 제공하여 Vite, Next.js, Webpack 파이프라인에 완벽히 연동됩니다.
            </p>
          </div>

          <div className="knds-grid knds-grid-cols-2 knds-gap-200 knds-mb-300">
            <div>
              <span className="knds-text-label-14-mono knds-text-red knds-mb-100" style={{ display: 'block' }}>
                KNDS.CONFIG.JS (CUSTOM TOKENS & CONTENT PATTERNS)
              </span>
              <pre className="knds-code-block" style={{ fontSize: '12px', maxHeight: '300px', overflowY: 'auto' }}>
{`/** @type {import('@knoblab/knds').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx,vue,svelte,html}'
  ],
  prefix: 'knds-',
  theme: {
    extend: {
      colors: {
        'surface-dark': '#09090b',
        'brand-accent': '#ad1d1d'
      },
      spacing: {
        'custom-header': '88px'
      }
    }
  },
  safelist: [
    'knds-indicator-dot',
    'knds-btn-primary'
  ]
};`}
              </pre>
            </div>

            <div>
              <span className="knds-text-label-14-mono knds-text-red knds-mb-100" style={{ display: 'block' }}>
                CLI EXECUTABLE & WATCH PIPELINE
              </span>
              <pre className="knds-code-block" style={{ fontSize: '12px', maxHeight: '300px', overflowY: 'auto' }}>
{`# 1. 일회성 온디맨드 빌드 및 Minify 압축
npx knds -o dist/output.min.css --minify
# Output: [KNDS JIT] Successfully built dist/output.min.css (4.57 KB in 14.5ms)

# 2. 실시간 파일 감지 (Watch Mode)
npx knds -o dist/output.css --watch
# Output: [KNDS Watcher] Watching source files for changes...

# 3. PostCSS 8 API 연동 (Vite / Next.js)
// postcss.config.js
import postcssKnds from '@knoblab/knds/postcss';
export default {
  plugins: [ postcssKnds({ config: './knds.config.js' }) ]
};`}
              </pre>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
